### PR TITLE
Fix updater so it behaves proper

### PR DESCRIPTION
**Pull request by lmsv-mx123**
Should fix concern on #33 for all users experimenting this issue

### CODE REVIEW

**Comment by conker-rsc** [comment]
Thanks for including my other fix as part of this

**Comment by conker-rsc** [comment]
There is also the `switchList` method in `Menu.java`, and another reference to `KEEP_SCROLLBAR_POS_MAGIC_PRAYER` in `Settings.java`

**Comment by lmsv-mx123** [comment]
> Thanks for including my other fix as part of this

No prob :) Glad you had placed the reference

**Comment by lmsv-mx123** [comment]
> There is a reference to `KEEP_SCROLLBAR_POS_MAGIC_PRAYER` in `Settings.java`
> 
> Also in `Menu.java`, there is the `switchList()` method, which should be kept in place because we can use it for friends/ignore list scroll later, BUT we can delete the commented-out code now that references `KEEP_SCROLLBAR_POS_MAGIC_PRAYER`

Should be good now

**Pull request merged**
